### ISSUE TITLE
Reversing transactions, confirm before reversing?

### ISSUE THREAD

**Issue by sonoftheweb** [Atunje/wallet#1]
Maybe it would be better to place the final reversal request behind a validation (email validation) to check if the user reversing transactions IS actually the account owner. This may be a feature that could be setup and opted into by the user.

**Comment by Atunje** [comment]
This is very thoughtful even though I feel it's a feature that should be built with the business logic of the client application using the package. Reversal could actually come from the owner of the account or from an authorized admin.
